### ISSUE TITLE
Do we have our own live version of dev docs?

### ISSUE THREAD

**Issue by akamicah** [overte-org/overte-dev-docs#1]
Do we have our own live version of dev docs?

User documentation for Overte still point users to Vircadia's dev docs

**Comment by ksuprynowicz** [comment]
Yes, here's our version:
https://apidocs.overte.org/

**Comment by akamicah** [comment]
> Yes, here's our version: https://apidocs.overte.org/

This documentation differs from this project - and from vircadia's dev docs (https://docs.vircadia.dev/). I suppose we could not use these dev docs at all and include anything that is useful from the dev docs in the main documentation?

**Comment by ksuprynowicz** [comment]
> I suppose we could not use these dev docs at all and include anything that is useful from the dev docs in the main documentation?

Sounds like a good idea to me, especially since there isn't much there and since our setup is a bit different already. Our global services are not centralized anymore for example.
